name: kipack
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - cupy-cuda111
      - pyfftw
      - params-mz @ git+https://github.com/Mayuyu/params.git
