name: kipack-dev
dependencies:
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - ipykernel
  - ipywidgets
  - flake8
  - black
  - pip
  - pip:
      - cupy-cuda101
      - pyfftw
      # For config file
      - params-mz @ git+https://github.com/Mayuyu/params.git
      # For tests
      - clawpack
