name: kipack
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - cupy-cuda102
      - pyfftw
      # For config file
      - params-mz @ git+https://github.com/Mayuyu/params.git
